# Generated by Django 4.2.2 on 2023-06-29 21:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('slug', models.SlugField()),
                ('dob', models.DateField(help_text='YYYY-MM-DD')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=20)),
                ('height', models.DecimalField(decimal_places=2, help_text='Enter your height in centimetres', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('weight', models.DecimalField(decimal_places=2, help_text='Enter your weight in kilograms', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('known_allergies', models.TextField(blank=True)),
                ('blood_type', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('symptoms', models.TextField()),
                ('diagnosis', models.TextField()),
                ('medication', models.TextField()),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
            ],
        ),
    ]
