# Generated by Django 4.2.2 on 2023-06-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_doctor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
    ]
